Module moduloLenguaje
    Public lang(130) As String
    Public Sub lenguaje(tipo)
        If tipo = "es" Then
            'LANGS DE INTERFAZ DE USUARIO frmInicioSesion
            lang(0) = "CONECTAR"
            lang(1) = "El estado de su conexion a la " & vbCrLf & "base de datos"
            lang(2) = "RECONECTAR"
            lang(3) = "Inicia sesión con tu Cuenta "
            lang(4) = "Usuario"
            lang(5) = "Usuario"
            lang(6) = "Contraseña"
            lang(7) = "Contraseña"
            lang(8) = "MOSTRAR"
            lang(9) = "OCULTAR"
            lang(10) = "Bienvenido al sistema de informacion, si olvidó su contraseña" & vbCrLf & " deberá contactar con un empleado desde el numero de telefono" & vbCrLf & " 775.359.8866"
            lang(11) = "Iniciar Sesion"
            lang(12) = "Registrarse Como Cliente"
            'LANGS DE INTERFAZ DE USUARIO frmRegistrarse
            lang(16) = "REGISTRARSE COMO CLIENTE"
            lang(17) = "DATOS DEL USUARIO"
            lang(18) = "Nombres"
            lang(19) = "Nombres"
            lang(20) = "Tipo de usuario"
            lang(21) = "es"
            lang(22) = "Telefono"
            lang(23) = "Email"
            lang(24) = "Email"
            lang(25) = "Sexo:"
            lang(26) = "es"
            lang(27) = "LIMPIAR"
            lang(28) = "REGISTRARSE"
            'LANGS DE INTERFAZ DE USUARIO frmVer
            lang(32) = "REGRESAR"
            'LANGS DE INTERFAZ DE USUARIO frmEditar
            lang(33) = "EDITAR PRODUCTO"
            lang(34) = "Nombre"
            lang(35) = "Nombre"
            lang(36) = "Imagen"
            lang(37) = "ruta://"
            lang(38) = "Subir Imagen"
            lang(39) = "Antes"
            lang(40) = "Antes"
            lang(41) = "Ahora"
            lang(42) = "Ahora"
            lang(43) = "ATRAS"
            lang(44) = "GUARDAR"
            'LANGS DE INTERFAZ DE USUARIO frmContactanos
            lang(49) = "CERRAR"
            'LANGS DE INTERFAZ DE USUARIO frmAgregarProductos
            lang(50) = "NOMBRE E IMAGEN"
            lang(51) = "PRECIOS"
            lang(52) = "AGREGAR"
            'LANGS DE INTERFAZ DE USUARIO frmEditarEliminarUsuarios
            lang(54) = "LISTADO DE USUARIOS"
            lang(55) = "EDITAR"
            lang(56) = "ELIMINAR"
            'LANGS DE INTERFAZ DE USUARIO frmEditarProductos
            lang(63) = "BUSQUEDAD"
            lang(64) = "BUSCAR"
            lang(65) = "Por: "
            lang(66) = "es"
            lang(67) = "Todos: "
            lang(68) = "Inactivos: "
            lang(69) = "Activos: "
            lang(70) = "LISTADO DE PRODUCTOS"
            lang(71) = "ESTADO"
            lang(72) = "ACTUALIZAR"
            'LANGS DE INTERFAZ DE USUARIO frmEliminarOnOffProductos
            lang(77) = "VER"
            'LANGS DE INTERFAZ DE USUARIO frmHome
            lang(114) = "Página de inicio"
            lang(115) = "Tienda"
            lang(116) = "Testimonios"
            lang(117) = "Usuarios"
            lang(118) = "Inventario de tienda"
            lang(119) = "Registros"
            lang(120) = "LISTADO DE ARTICULOS"
            lang(121) = "Contactanos"
            lang(122) = "CERRAR SESION"
            lang(123) = "Ayuda"
            'LANGS DE INTERFAZ DE USUARIO frmInicio
            lang(79) = "PAGINA DE INICIO"
            lang(80) = "PAGINA WEB"
            'LANGS DE INTERFAZ DE USUARIO frmListadoArticulos
            lang(81) = "Seleccione un articulo para ver su foto"
            lang(82) = "ARTICULOS"
            lang(83) = "TOTAL:"
            lang(84) = "ARTICULOS EN STOCK:"
            lang(85) = "ARTICULOS TERMINADOS:"
            'LANGS DE INTERFAZ DE USUARIO frmProductos
            lang(87) = "AGREGAR PRODUCTO"
            lang(88) = "ELIMINAR PRODUCTOS"
            lang(89) = "EDITAR PRODUCTOS"
            lang(90) = "PRODUCTOS"
            'LANGS DE INTERFAZ DE USUARIO frmRegistros
            lang(91) = "REFRESCAR"
            lang(92) = "Ordenar por:"
            lang(93) = "es"
            lang(94) = "LISTADO DE REGISTROS"
            lang(124) = "REGISTROS"
            'LANGS DE INTERFAZ DE USUARIO frmTestimonios
            lang(98) = "TESTIMONIOS"
            lang(99) = "Agregar"
            lang(100) = "TITULO :  "
            lang(101) = "No agregado"
            lang(102) = "MENSAJE"
            lang(103) = "TESTIMONIO POR CLIENTES"
            'LANGS DE INTERFAZ DE USUARIO frmUsuarios
            lang(111) = "AGREGAR USUARIO"
            lang(112) = "EDITAR Y ELIMINAR USUARIOS"
            lang(113) = "USUARIOS"
            'LANGS DE CODIGO FUENTE
            lang(13) = "Error ::: Campos vacíos"
            lang(14) = "Error ::: Datos incorrectos"
            lang(15) = "Error ::: Error del servidor"
            lang(29) = "Error ::: Ya existe un usuario con ese nombre"
            lang(30) = "Ok ::: Usuario registrado"
            lang(31) = "Ok ::: Campos limpiados"
            lang(45) = "Error ::: Debe hacer algún cambio para hacer la actualizacion"
            lang(46) = "Error ::: Archivo no permitido"
            lang(47) = "Ok ::: Producto actualizado"
            lang(48) = "Ok ::: Imagen subida"
            lang(53) = "Ok ::: Cajas de texto limpiadas"
            lang(57) = "Ok ::: Usuario actualizado"
            lang(58) = "Ok ::: Usuario eliminado"
            lang(59) = "Seleccione una fila"
            lang(60) = "Ok ::: Usuarios cargados"
            lang(61) = "Ok ::: No hay usuarios para mostrar"
            lang(62) = "seleccionado"
            lang(73) = "Ok ::: Productos cargados"
            lang(74) = "Ok ::: No hay productos para mostrar"
            lang(75) = "Activo"
            lang(76) = "Inactivo"
            lang(78) = "Ok ::: Producto eliminado"
            lang(86) = "LISTADOS CARGADOS"
            lang(95) = "SELECCIONE EL TIPO DE ORDENAMIENTO QUE DESEE"
            lang(96) = "Ok ::: Registros cargados"
            lang(97) = "Ok ::: No hay registros para mostrar"
            lang(104) = "Actualizar"
            lang(105) = "ACTIVAR"
            lang(106) = "DESACTIVAR"
            lang(107) = "Ok ::: Testimonios cargados"
            lang(108) = "Ok ::: No hay testimonios para mostrar"
            lang(109) = "Ok ::: Testimonio activado"
            lang(110) = "Ok ::: Testimonio desactivado"
            lang(125) = "Productos"
            lang(126) = "Fecha"
            lang(127) = "Que hizo"
            lang(128) = "Precio"
            lang(129) = "Ruta"
        ElseIf tipo = "en" Then
            'LANGS DE INTERFAZ DE USUARIO frmInicioSesion
            lang(0) = "CONNECT"
            lang(1) = "The state of your connection to " & vbCrLf & "the database"
            lang(2) = "RECONNECT"
            lang(3) = "Log in with your account"
            lang(4) = "User"
            lang(5) = "User"
            lang(6) = "Password"
            lang(7) = "Password"
            lang(8) = "SHOW"
            lang(9) = "HIDE"
            lang(10) = "Welcome to the information system, if you forgot your password " & vbCrLf & " you should contact an employee from the phone number " & vbCrLf & " 775.359.8866"
            lang(11) = "Log in"
            lang(12) = "Register as a Client"
            'LANGS DE INTERFAZ DE USUARIO frmRegistrarse
            lang(16) = "REGISTER AS A CUSTOMER"
            lang(17) = "USER DATA"
            lang(18) = "Names"
            lang(19) = "Names"
            lang(20) = "Type of user"
            lang(21) = "en"
            lang(22) = "Phone"
            lang(25) = "Sex:"
            lang(26) = "en"
            lang(27) = "CLEAN"
            lang(28) = "CHECK IN"
            'LANGS DE INTERFAZ DE USUARIO frmVer
            lang(32) = "GO BACK"
            'LANGS DE INTERFAZ DE USUARIO frmEditar
            lang(33) = "EDIT PRODUCT"
            lang(34) = "Name"
            lang(35) = "Name"
            lang(36) = "Image"
            lang(37) = "route://"
            lang(38) = "Upload Image"
            lang(39) = "Before"
            lang(40) = "Before"
            lang(41) = "Now"
            lang(42) = "Now"
            lang(43) = "GO BACK"
            lang(44) = "SAVE"
            'LANGS DE INTERFAZ DE USUARIO frmContactanos
            lang(49) = "CLOSE"
            'LANGS DE INTERFAZ DE USUARIO frmAgregarProductos
            lang(50) = "NAME AND IMAGE"
            lang(51) = "PRICES"
            lang(52) = "ADD"
            'LANGS DE INTERFAZ DE USUARIO frmEditarEliminarUsuarios
            lang(54) = "LIST OF USERS"
            lang(55) = "EDIT"
            lang(56) = "DELETE"
            'LANGS DE INTERFAZ DE USUARIO frmEditarProductos
            lang(63) = "SEARCH"
            lang(64) = "SEARCH"
            lang(65) = "By: "
            lang(66) = "en"
            lang(67) = "All: "
            lang(68) = "Inactive: "
            lang(69) = "Active: "
            lang(70) = "PRODUCT LIST"
            lang(71) = "STATE"
            lang(72) = "UPDATE"
            'LANGS DE INTERFAZ DE USUARIO frmEliminarOnOffProductos
            lang(77) = "WATCH"
            'LANGS DE INTERFAZ DE USUARIO frmHome
            lang(114) = "Homepage"
            lang(115) = "Store"
            lang(116) = "Testimonies"
            lang(117) = "Users"
            lang(118) = "Machine store inventory"
            lang(119) = "Logs"
            lang(120) = "ARTICLE LIST"
            lang(121) = "Contact us"
            lang(122) = "GET OUT"
            lang(123) = "Help"
            'LANGS DE INTERFAZ DE USUARIO frmInicio
            lang(79) = "HOMEPAGE"
            lang(80) = "WEB SITE"
            'LANGS DE INTERFAZ DE USUARIO frmListadoArticulos
            lang(81) = "Select an item to see your photo"
            lang(82) = "ARTICLES"
            lang(83) = "TOTAL:"
            lang(84) = "STOCK ITEMS:"
            lang(85) = "FINISHED ITEMS:"
            'LANGS DE INTERFAZ DE USUARIO frmProductos
            lang(87) = "ADD PRODUCT"
            lang(88) = "DELETE PRODUCTS"
            lang(89) = "EDIT PRODUCTS"
            lang(90) = "PRODUCTS"
            'LANGS DE INTERFAZ DE USUARIO frmRegistros
            lang(91) = "REFRESH"
            lang(92) = "Sort by:"
            lang(93) = "en"
            lang(94) = "LIST OF RECORDS"
            lang(124) = "RECORDS"
            'LANGS DE INTERFAZ DE USUARIO frmTestimonios
            lang(98) = "TESTIMONIES"
            lang(99) = "Add"
            lang(100) = "TITLE :  "
            lang(101) = "Not added"
            lang(102) = "MESSAGE"
            lang(103) = "CUSTOMER TESTIMONY"
            'LANGS DE INTERFAZ DE USUARIO frmUsuarios
            lang(111) = "ADD USER"
            lang(112) = "EDIT AND ELIMINATE USERS"
            lang(113) = "USERS"
            'LANGS DE CODIGO FUENTE
            lang(13) = "Error ::: Empty fields"
            lang(14) = "Error ::: Incorrect data"
            lang(15) = "Error ::: Server error"
            lang(29) = "Error ::: A user with that name already exists"
            lang(30) = "Ok ::: Registered user"
            lang(31) = "Ok ::: Fields Cleaned"
            lang(45) = "Error ::: There must be some change to make the update"
            lang(46) = "Error ::: File not allowed"
            lang(47) = "Ok ::: Updated product"
            lang(48) = "Ok ::: Image uploaded"
            lang(53) = "Ok ::: Text boxes cleaned"
            lang(57) = "Ok ::: User updated"
            lang(58) = "Ok ::: User Deleted"
            lang(59) = "Select a row"
            lang(60) = "Ok ::: Users uploaded"
            lang(61) = "Ok ::: There are no users to show"
            lang(62) = "selected"
            lang(73) = "Ok ::: Loaded Products"
            lang(74) = "Ok ::: There are no products to display"
            lang(75) = "Active"
            lang(76) = "Inactive"
            lang(78) = "Ok ::: Product removed"
            lang(86) = "LOADED LISTS"
            lang(95) = "SELECT THE TYPE OF ORDERING YOU WANT"
            lang(96) = "Ok ::: Loaded Logs"
            lang(97) = "Ok ::: There are no records to show"
            lang(104) = "To update"
            lang(105) = "ACTIVATE"
            lang(106) = "DEACTIVATE"
            lang(107) = "Ok ::: Loaded testimonials"
            lang(108) = "Ok ::: There are no testimonials to show"
            lang(109) = "Ok ::: Testimony activated"
            lang(110) = "Ok ::: Testimony deactivated"
            lang(125) = "Products"
            lang(126) = "Date"
            lang(127) = "What did"
            lang(128) = "Price"
            lang(129) = "Route"
        End If
    End Sub
End Module
